#api http test for vscode rest client

## variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0MSwibmFtZSI6InRlc3QudXNlciIsInVzZXJuYW1lIjoiYWJiYSIsImVtYWlsIjoiYWRtaS5kZGRlQGV4YW1wbGUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjI3NzQzNTYsImV4cCI6MTc2MzYzODM1Nn0.Wo-KpUyG0A-EW6ZH1B6QTJhBsB45a5ZaBtFVI813QYU
@admin-token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozOCwibmFtZSI6ImFkbWluYWRtaW4iLCJ1c2VybmFtZSI6ImFkbWluMyIsImVtYWlsIjoiYWRtaW4uZG9lQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzYyNzczOTEzLCJleHAiOjE3NjM2Mzc5MTN9.1e1vn1LicwRWx3EX7tLVUglFtkFBj4eNQ_8RI-tY4HM
######## CATS ########
###get cats
GET HTTP://localhost:3000/api/v1/cats
Authorization: Bearer {{token}}

###get cat by id
GET http://localhost:3000/api/v1/cats/41
Authorization: Bearer {{token}}


### create cat WITH FILE 
POST http://localhost:3000/api/v1/cats
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=BOUNDARY

--BOUNDARY
Content-Disposition: form-data; name="cat_name"

Kisuliini
--BOUNDARY
Content-Disposition: form-data; name="weight"

420
--BOUNDARY
Content-Disposition: form-data; name="birthdate"

2021-10-12
--BOUNDARY
Content-Disposition: form-data; name="file"; filename="puppy.jpg"
Content-Type: image/jpeg

< ./puppy.jpg
--BOUNDARY--


###put test
PUT http://localhost:3000/api/v1/cats/43
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "cat_name": "Liini-kisu",
    "weight": 66,
    "owner": 40,
    "filename": "f3dasdfkjsdfhgasdf",
    "birthdate": "2021-10-12"
}

###delete test
DELETE http://localhost:3000/api/v1/cats/38
Authorization: Bearer {{token}}

######## USERS ########

### Get all users
GET http://localhost:3000/api/v1/users
Authorization: Bearer {{token}}

### Get user by id
GET http://localhost:3000/api/v1/users/37
Authorization: Bearer {{token}}

### Create user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "test.user",
  "username": "abba",
  "email": "admi.ddde@example.com",
  "password": "password",
  "role": "user"
}

### Update user
PUT http://localhost:3000/api/v1/users/38
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "dohn.joe",
  "username": "dohnjoe",
  "email": "dohn.joe@example.com",
  "password": "passowrd"
}

### Delete user
DELETE http://localhost:3000/api/v1/users/37
Authorization: Bearer {{token}}

### get cats by user id
GET http://localhost:3000/api/v1/users/cats/37
Authorization: Bearer {{token}}

### get cats owner name by cats id
GET http://localhost:3000/api/v1/cats/owner/37
Authorization: Bearer {{token}}

### test login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "abba",
  "password": "password"
}

### log in admin
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin3",
  "password": "password"
}

### Post login
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer {{token}}

######## ADMIN TESTS ########

### Modify as admin

### Cat:
PUT http://localhost:3000/api/v1/cats/43
Authorization: Bearer {{admin-token}}
Content-Type: application/json

{
    "cat_name": "Liini-kisu72",
    "weight": 22,
    "owner": 40,
    "filename": "f3dasdfkjsdfhgasdf",
    "birthdate": "2021-10-12"
}

### User:
PUT http://localhost:3000/api/v1/users/37
Authorization: Bearer {{admin-token}}
Content-Type: application/json

{
  "name": "dohn.joe",
  "username": "dohnjoe",
  "email": "dohn.joe@example.com",
  "password": "passowrd"
}

### Admin delete test

## User:
DELETE http://localhost:3000/api/v1/users/40
Authorization: Bearer {{admin-token}}

### Cat:
DELETE http://localhost:3000/api/v1/cats/45
Authorization: Bearer {{admin-token}}