#api http test for vscode rest client
######## CATS ########
###get cats
GET HTTP://localhost:3000/api/v1/cats

###get cat by id
GET http://localhost:3000/api/v1/cats/41
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozOCwibmFtZSI6ImpvaG4uZG9lIiwidXNlcm5hbWUiOiJqb2huZG9lIiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzYyNTE2MDczLCJleHAiOjE3NjI2MDI0NzN9.FBCeKndcHFSHChXiSx7H4Y1xBGpyXlOH3V99oQR8xBM


### create cat WITH FILE 
POST http://localhost:3000/api/v1/cats
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="cat_name"

Kisuliini
------Boundary
Content-Disposition: form-data; name="weight"

420
------Boundary
Content-Disposition: form-data; name="owner"

37

------Boundary
Content-Disposition: form-data; name="file"; filename="puppy.jpg"
Content-Type: image/png

< ./puppy.jpg

------Boundary
Content-Disposition: form-data; name="birthdate"

2021-10-12
------Boundary--
###post test
POST http://localhost:3000/api/v1/cats/
Content-Type: application/json

{
    "cat_id": 69420,
    "cat_name": "Kisuliini",
    "weight": 420,
    "owner": 3602,
    "filename": "f3dasdfkjsdfhgasdf",
    "birthdate": "2021-10-12"
}

###put test
PUT http://localhost:3000/api/v1/cats/44
Content-Type: application/json

{
    "cat_id": 45,
    "cat_name": "Liini-kisu",
    "weight": 66,
    "owner": 37,
    "filename": "f3dasdfkjsdfhgasdf",
    "birthdate": "2021-10-12"
}

###delete test
DELETE http://localhost:3000/api/v1/cats/45

######## USERS ########

### Get all users
GET http://localhost:3000/api/v1/users

### Get user by id
GET http://localhost:3000/api/v1/users/37

### Create user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "john.doe",
  "username": "johndoe",
  "email": "john.doe@example.com",
  "password": "passowrd",
  "role": "user"
}

### Update user
PUT http://localhost:3000/api/v1/users/38
Content-Type: application/json

{
  "name": "dohn.joe",
  "username": "dohnjoe",
  "email": "dohn.joe@example.com",
  "role": "user",
  "password": "passowrd"
}

### Delete user
DELETE http://localhost:3000/api/v1/users/123

### get cats by user id
GET http://localhost:3000/api/v1/users/cats/37

### get cats owner name by cats id
GET http://localhost:3000/api/v1/cats/owner/37

### test login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "johndoe",
  "password": "passowrd"
}


### Post login
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozOCwibmFtZSI6ImpvaG4uZG9lIiwidXNlcm5hbWUiOiJqb2huZG9lIiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzYyNTE2MDczLCJleHAiOjE3NjI2MDI0NzN9.FBCeKndcHFSHChXiSx7H4Y1xBGpyXlOH3V99oQR8xBM
